---
name: Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Run Go Test
      id: gotest
      uses: docker://golang:1.13
      with:
        args: go test */***
        workdir: /github/workspace