---
name: Test

on: [push]

jobs:
  unittest:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run Go Test
      id: gotest
      uses: docker://golang:1.13
      with:
        args: go test ./...

  # TODO: https://github.com/dominikh/go-tools
  staticanalysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run Go Vet
      id: govet
      uses: docker://golang:1.13
      with:
        args: go vet ./...

  security:
    name: Security Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run gosec
      uses: docker://securego/gosec:v2.1.0
      with:
        args: ./...